#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FormSample.Droid.Resource", IsApplication=true)]

namespace FormSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::FormSample.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::FormSample.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::FormSample.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::FormSample.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::FormSample.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::FormSample.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::FormSample.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::FormSample.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::FormSample.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::FormSample.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::FormSample.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::FormSample.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::FormSample.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::FormSample.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::FormSample.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::FormSample.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::FormSample.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::FormSample.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::FormSample.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::FormSample.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::FormSample.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::FormSample.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::FormSample.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::FormSample.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::FormSample.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::FormSample.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::FormSample.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::FormSample.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::FormSample.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::FormSample.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::FormSample.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::FormSample.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::FormSample.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::FormSample.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::FormSample.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::FormSample.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::FormSample.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::OxyPlot.XamarinFormsAndroid.Resource.String.library_name = global::FormSample.Droid.Resource.String.library_name;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::FormSample.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::FormSample.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_active_month_bg = global::FormSample.Droid.Resource.Color.calendar_active_month_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_bg = global::FormSample.Droid.Resource.Color.calendar_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_divider = global::FormSample.Droid.Resource.Color.calendar_divider;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_highlighted_day_bg = global::FormSample.Droid.Resource.Color.calendar_highlighted_day_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_inactive_month_bg = global::FormSample.Droid.Resource.Color.calendar_inactive_month_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_selected_day_bg = global::FormSample.Droid.Resource.Color.calendar_selected_day_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_selected_range_bg = global::FormSample.Droid.Resource.Color.calendar_selected_range_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_active = global::FormSample.Droid.Resource.Color.calendar_text_active;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_inactive = global::FormSample.Droid.Resource.Color.calendar_text_inactive;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_selected = global::FormSample.Droid.Resource.Color.calendar_text_selected;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_selector = global::FormSample.Droid.Resource.Color.calendar_text_selector;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_unselectable = global::FormSample.Droid.Resource.Color.calendar_text_unselectable;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_day_headers_paddingbottom = global::FormSample.Droid.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_month_title_bottommargin = global::FormSample.Droid.Resource.Dimension.calendar_month_title_bottommargin;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_month_topmargin = global::FormSample.Droid.Resource.Dimension.calendar_month_topmargin;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_text_medium = global::FormSample.Droid.Resource.Dimension.calendar_text_medium;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_text_small = global::FormSample.Droid.Resource.Dimension.calendar_text_small;
			global::Xamarin.Forms.Labs.Droid.Resource.Drawable.ad16 = global::FormSample.Droid.Resource.Drawable.ad16;
			global::Xamarin.Forms.Labs.Droid.Resource.Drawable.calendar_bg_selector = global::FormSample.Droid.Resource.Drawable.calendar_bg_selector;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.calendar_grid = global::FormSample.Droid.Resource.Id.calendar_grid;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.calendar_view = global::FormSample.Droid.Resource.Id.calendar_view;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.title = global::FormSample.Droid.Resource.Id.title;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.calendar_picker = global::FormSample.Droid.Resource.Layout.calendar_picker;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.dialog = global::FormSample.Droid.Resource.Layout.dialog;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.month = global::FormSample.Droid.Resource.Layout.month;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.week = global::FormSample.Droid.Resource.Layout.week;
			global::Xamarin.Forms.Labs.Droid.Resource.String.day_name_format = global::FormSample.Droid.Resource.String.day_name_format;
			global::Xamarin.Forms.Labs.Droid.Resource.String.full_date_format = global::FormSample.Droid.Resource.String.full_date_format;
			global::Xamarin.Forms.Labs.Droid.Resource.String.invalid_date = global::FormSample.Droid.Resource.String.invalid_date;
			global::Xamarin.Forms.Labs.Droid.Resource.String.library_name = global::FormSample.Droid.Resource.String.library_name;
			global::Xamarin.Forms.Labs.Droid.Resource.String.month_name_format = global::FormSample.Droid.Resource.String.month_name_format;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell = global::FormSample.Droid.Resource.Style.CalendarCell;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell_CalendarDate = global::FormSample.Droid.Resource.Style.CalendarCell_CalendarDate;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell_DayHeader = global::FormSample.Droid.Resource.Style.CalendarCell_DayHeader;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarTitle = global::FormSample.Droid.Resource.Style.CalendarTitle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int ahBarColor = 2130771974;
			
			// aapt resource value: 0x7f01000e
			public const int ahBarLength = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int ahBarWidth = 2130771981;
			
			// aapt resource value: 0x7f01000b
			public const int ahCircleColor = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahDelayMillis = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public const int ahRadius = 2130771980;
			
			// aapt resource value: 0x7f010007
			public const int ahRimColor = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int ahRimWidth = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int ahSpinSpeed = 2130771977;
			
			// aapt resource value: 0x7f010003
			public const int ahText = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int ahTextColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahTextSize = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int axisTitle = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int labelColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int labelSize = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int calendar_active_month_bg = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int calendar_bg = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int calendar_divider = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int calendar_highlighted_day_bg = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int calendar_inactive_month_bg = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int calendar_selected_day_bg = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int calendar_selected_range_bg = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int calendar_text_active = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int calendar_text_inactive = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int calendar_text_selected = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int calendar_text_selector = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int calendar_text_unselectable = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int calendar_day_headers_paddingbottom = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int calendar_month_title_bottommargin = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int calendar_month_topmargin = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int calendar_text_medium = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_text_small = 2131034116;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int aboutus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ad16 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AmendDetail = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int calendar_bg_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ContactAgency = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ContactMap = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ContactPhoneNumber = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Google = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int homeheader = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_errorstatus = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_successstatus = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int LinkedIn = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int logo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int logo_large_c9y13k30 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int menu_icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int monoandroidsplash = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int MyContractors = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int PayCalculator = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Paychart = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int roundedbg = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int roundedbgdark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int s960 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int slideout = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int slideout2x = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080011
			public const int MyButton = 2131230737;
			
			// aapt resource value: 0x7f080006
			public const int axisLayout = 2131230726;
			
			// aapt resource value: 0x7f080013
			public const int calendar_grid = 2131230739;
			
			// aapt resource value: 0x7f080000
			public const int calendar_view = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int chartAreaLayout = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int chartTitle = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int gridLineLayout = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int iconView = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int label = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int legendHeader = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int legendItemsLayout = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int legendScrollView = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int legendViewGroup = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public const int loadingImage = 2131230735;
			
			// aapt resource value: 0x7f08000d
			public const int loadingProgressBar = 2131230733;
			
			// aapt resource value: 0x7f080010
			public const int loadingProgressWheel = 2131230736;
			
			// aapt resource value: 0x7f080001
			public const int rootLayout = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int seriesLayout = 2131230725;
			
			// aapt resource value: 0x7f08000e
			public const int textViewStatus = 2131230734;
			
			// aapt resource value: 0x7f080012
			public const int title = 2131230738;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_picker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int chart_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int chart_legend = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int chart_legend_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int loading = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int loadingimage = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int loadingprogress = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int month = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int week = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060007
			public const int ApplicationName = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int Hello = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int app_name = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int day_name_format = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int full_date_format = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int invalid_date = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int month_name_format = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070004
			public const int AppTheme = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int Mono_Android_Theme_Splash = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ChartAxis = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int ChartAxis_axisTitle = 2;
			
			// aapt resource value: 0
			public const int ChartAxis_labelColor = 0;
			
			// aapt resource value: 1
			public const int ChartAxis_labelSize = 1;
			
			public static int[] ProgressWheel = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
